#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

#include "XamlBindingInfo.g.h"

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class SwapChainPanel;
                ref class Button;
                ref class Flyout;
                ref class TextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace BBPlayer
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class OpenGLESPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
        class OpenGLESPage_obj1_Bindings;
    
        ::XamlBindingInfo::XamlBindings^ Bindings;
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Controls::Grid^ TitleBar;
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ swapChainPanel;
        private: ::Windows::UI::Xaml::Controls::Button^ cocos2d_editbox;
        private: ::Windows::UI::Xaml::Controls::Flyout^ cocos2d_editbox_flyout;
        private: ::Windows::UI::Xaml::Controls::Grid^ cocos2d_editbox_grid;
        private: ::Windows::UI::Xaml::Controls::Button^ cocos2d_editbox_done;
        private: ::Windows::UI::Xaml::Controls::Button^ cocos2d_editbox_cancel;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ BackgroundElement;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ AppName;
        private: ::Windows::UI::Xaml::Controls::Button^ FullScreenModeToggle;
    };
}

